
export interface Country {
    Name: string
}

export const Countries: Country[] = [
    { Name: "Afghanistan" },
    { Name: "Albania" },
    { Name: "Algeria" },
    { Name: "America" },
    { Name: "Andorra" },
    { Name: "Angola" },
    { Name: "Antigua" },
    { Name: "Argentina" },
    { Name: "Armenia" },
    { Name: "Australia" },
    { Name: "Austria" },
    { Name: "Azerbaijan" },
    { Name: "Bahamas" },
    { Name: "Bahrain" },
    { Name: "Bangladesh" },
    { Name: "Barbados" },
    { Name: "Belarus" },
    { Name: "Belgium" },
    { Name: "Belize" },
    { Name: "Benin" },
    { Name: "Bhutan" },
    { Name: "Bissau" },
    { Name: "Bolivia" },
    { Name: "Bosnia" },
    { Name: "Botswana" },
    { Name: "Brazil" },
    { Name: "British" },
    { Name: "Brunei" },
    { Name: "Bulgaria" },
    { Name: "Burkina" },
    { Name: "Burma" },
    { Name: "Burundi" },
    { Name: "Cambodia" },
    { Name: "Cameroon" },
    { Name: "Canada" },
    { Name: "Cape Verde" },
    { Name: "Central African Republic" },
    { Name: "Chad" },
    { Name: "Chile" },
    { Name: "China" },
    { Name: "Colombia" },
    { Name: "Comoros" },
    { Name: "Congo" },
    { Name: "Costa Rica" },
    { Name: "country debt" },
    { Name: "Croatia" },
    { Name: "Cuba" },
    { Name: "Cyprus" },
    { Name: "Czech" },
    { Name: "Denmark" },
    { Name: "Djibouti" },
    { Name: "Dominica" },
    { Name: "East Timor" },
    { Name: "Ecuador" },
    { Name: "Egypt" },
    { Name: "El Salvador" },
    { Name: "Emirate" },
    { Name: "England" },
    { Name: "Eritrea" },
    { Name: "Estonia" },
    { Name: "Ethiopia" },
    { Name: "Fiji" },
    { Name: "Finland" },
    { Name: "France" },
    { Name: "Gabon" },
    { Name: "Gambia" },
    { Name: "Georgia" },
    { Name: "Germany" },
    { Name: "Ghana" },
    { Name: "Great Britain" },
    { Name: "Greece" },
    { Name: "Grenada" },
    { Name: "Grenadines" },
    { Name: "Guatemala" },
    { Name: "Guinea" },
    { Name: "Guyana" },
    { Name: "Haiti" },
    { Name: "Herzegovina" },
    { Name: "Honduras" },
    { Name: "Hungary" },
    { Name: "Iceland" },
    { Name: "in usa" },
    { Name: "India" },
    { Name: "Indonesia" },
    { Name: "Iran" },
    { Name: "Iraq" },
    { Name: "Ireland" },
    { Name: "Israel" },
    { Name: "Italy" },
    { Name: "Ivory Coast" },
    { Name: "Jamaica" },
    { Name: "Japan" },
    { Name: "Jordan" },
    { Name: "Kazakhstan" },
    { Name: "Kenya" },
    { Name: "Kiribati" },
    { Name: "Korea" },
    { Name: "Kosovo" },
    { Name: "Kuwait" },
    { Name: "Kyrgyzstan" },
    { Name: "Laos" },
    { Name: "Latvia" },
    { Name: "Lebanon" },
    { Name: "Lesotho" },
    { Name: "Liberia" },
    { Name: "Libya" },
    { Name: "Liechtenstein" },
    { Name: "Lithuania" },
    { Name: "Luxembourg" },
    { Name: "Macedonia" },
    { Name: "Madagascar" },
    { Name: "Malawi" },
    { Name: "Malaysia" },
    { Name: "Maldives" },
    { Name: "Mali" },
    { Name: "Malta" },
    { Name: "Marshall" },
    { Name: "Mauritania" },
    { Name: "Mauritius" },
    { Name: "Mexico" },
    { Name: "Micronesia" },
    { Name: "Moldova" },
    { Name: "Monaco" },
    { Name: "Mongolia" },
    { Name: "Montenegro" },
    { Name: "Morocco" },
    { Name: "Mozambique" },
    { Name: "Myanmar" },
    { Name: "Namibia" },
    { Name: "Nauru" },
    { Name: "Nepal" },
    { Name: "Netherlands" },
    { Name: "New Zealand" },
    { Name: "Nicaragua" },
    { Name: "Niger" },
    { Name: "Nigeria" },
    { Name: "Norway" },
    { Name: "Oman" },
    { Name: "Pakistan" },
    { Name: "Palau" },
    { Name: "Panama" },
    { Name: "Papua" },
    { Name: "Paraguay" },
    { Name: "Peru" },
    { Name: "Philippines" },
    { Name: "Poland" },
    { Name: "Portugal" },
    { Name: "Qatar" },
    { Name: "Romania" },
    { Name: "Russia" },
    { Name: "Rwanda" },
    { Name: "Samoa" },
    { Name: "San Marino" },
    { Name: "Sao Tome" },
    { Name: "Saudi Arabia" },
    { Name: "scotland" },
    { Name: "scottish" },
    { Name: "Senegal" },
    { Name: "Serbia" },
    { Name: "Seychelles" },
    { Name: "Sierra Leone" },
    { Name: "Singapore" },
    { Name: "Slovakia" },
    { Name: "Slovenia" },
    { Name: "Solomon" },
    { Name: "Somalia" },
    { Name: "South Africa" },
    { Name: "South Sudan" },
    { Name: "Spain" },
    { Name: "Sri Lanka" },
    { Name: "St. Kitts" },
    { Name: "St. Lucia" },
    { Name: "St Kitts" },
    { Name: "St Lucia" },
    { Name: "Saint Kitts" },
    { Name: "Santa Lucia" },
    { Name: "Sudan" },
    { Name: "Suriname" },
    { Name: "Swaziland" },
    { Name: "Sweden" },
    { Name: "Switzerland" },
    { Name: "Syria" },
    { Name: "Taiwan" },
    { Name: "Tajikistan" },
    { Name: "Tanzania" },
    { Name: "Thailand" },
    { Name: "Tobago" },
    { Name: "Togo" },
    { Name: "Tonga" },
    { Name: "Trinidad" },
    { Name: "Tunisia" },
    { Name: "Turkey" },
    { Name: "Turkmenistan" },
    { Name: "Tuvalu" },
    { Name: "Uganda" },
    { Name: "Ukraine" },
    { Name: "United Kingdom" },
    { Name: "United States" },
    { Name: "Uruguay" },
    { Name: "USA" },
    { Name: "Uzbekistan" },
    { Name: "Vanuatu" },
    { Name: "Vatican" },
    { Name: "Venezuela" },
    { Name: "Vietnam" },
    { Name: "wales" },
    { Name: "welsh" },
    { Name: "Yemen" },
    { Name: "Zambia" },
    { Name: "Zimbabwe" }
];